#!/bin/bash

BUNDLE_IDENTIFIER='tw.ithoan.inputmethod.ThoanTaigi'
INSTALL_LOCATION='/Library/Input Methods'

cd "$(dirname $0)"
PROJECT_ROOT=$(cd ..; pwd)

get_app_version() {
    sed -n '/CFBundleShortVersionString/{n;s/.*<string>\(.*\)<\/string>.*/\1/;p;}' $@
}

APP_VERSION=$(get_app_version "${PROJECT_ROOT}/Info.plist")

#     --info PackageInfo \
pkgbuild \
    --root "${PROJECT_ROOT}/build/Release" \
    --component-plist Squirrel-component.plist \
    --identifier "${BUNDLE_IDENTIFIER}" \
    --version ${APP_VERSION} \
    --install-location "${INSTALL_LOCATION}" \
    --scripts "${PROJECT_ROOT}/scripts" \
    ../Release/ThoanTaigi_v${APP_VERSION}.pkg
